# Generated by Django 4.0.3 on 2022-05-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('reactions', '0002_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='firebaseUserId',
            new_name='firebaseUserUUID',
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('firebaseUserUUID', 'post')},
        ),
    ]
