# Generated by Django 4.0.3 on 2022-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0003_rename_firebaseuserid_view_firebaseuseruuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='firebaseUserUUID',
            field=models.CharField(max_length=1000),
        ),
    ]
