# Generated by Django 4.0.3 on 2022-06-09 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('reactions', '0005_view_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='firebaseUserUUID',
            new_name='firebase_user_id',
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('firebase_user_id', 'post')},
        ),
    ]
