# Generated by Django 4.0.3 on 2022-06-09 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0006_rename_firebaseuseruuid_view_firebase_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='created_at',
            new_name='first_seen',
        ),
        migrations.AddField(
            model_name='view',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
